### PR TITLE
README improvements

### PR DESCRIPTION
**Pull request by marendowski**
I "refactored" README, moved some text, and added new section for Troubleshooting.

### CODE REVIEW

**Comment by marendowski** [comment]
It looks like I messed something up.

**Comment by marendowski** [comment]
@sseemayer could you help me with it? I'm new to branch conflicts. :/

**Comment by marendowski** [comment]
It looks like I fixed it.

**Comment by sseemayer** [comment]
Sweet - thanks a lot for the corrections!

**Pull request merged**
